# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-27 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190926_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField()),
                ('username', models.TextField()),
                ('email', models.TextField()),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('postalcode', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='table1',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
