# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-27 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20190927_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='postalcode',
            field=models.TextField(),
        ),
    ]
